[workspace]
resolver = "2"
members = [ "api", "client", "cli", "network", "program", "example" ]

[workspace.package]
version = "0.2.1"
edition = "2021"
license = "Apache-2.0"
homepage = "https://tapedrive.io"
description = "Your data, permanently recorded â€” uncensorable, uneditable, and here for good."
repository = "https://github.com/tapedrive-io/tape"
readme = "./README.md"
keywords = ["solana", "crypto", "mining"]

[workspace.dependencies]
tape-api = { version = "0.2.1", path = "./api" }
tape-client = { version = "0.2.1", path = "./client" }
tape-network = { version = "0.2.1", path = "./network" }
tape-program = { version = "0.2.1", path = "./program" }

crankx = { version = "0.2.2", features = ["solana"] }
packx = { version = "0.4.1", features = ["solana"] }

# program dependencies
bytemuck = "1.14.3"
bytemuck_derive = "1.7.0"
num_enum = "0.7.2"
brine-tree = { version = "0.6.2", features = ["solana"] }
array-const-fn-init = "0.1.1"
const-crypto = "0.3.0"

# solana-specific
solana-client = "=2.1"
solana-program = "=2.1"
solana-sdk = "=2.1"
solana-transaction-status = "=2.1"
solana-account-decoder = "=2.1"
solana-transaction-status-client-types = "=2.1"

steel = { version="4.0.0", features = ["spl"] }
litesvm = "0.5.0"

mpl-token-metadata = "5.1"
spl-token = { version = "^4", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "^6", features = [ "no-entrypoint" ] } 

# client-specific
anyhow = "1.0"
flate2 = "1.0"
blake3 = "1.8.2"
bincode = "1.3"
base64 = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
rand = "0.8"
thiserror = "2.0.12"

# cli-specific
clap = { version = "4.5", features = ["derive"] }
colored = "3.0.0"
dialoguer = "0.11.0"
dirs = "5.0"
tokio = { version = "1.37", features = ["full"] }
reqwest = { version = "0.12", features = ["default", "json",] }
indicatif = "0.17"
console = "0.15"
mime = "0.3"
mime_guess = "2.0"
log = "0.4"
env_logger = "0.11"

# network-specific
futures = "0.3"
rocksdb = {version = "0.23.0", features = ["multi-threaded-cf"]}
tempdir = "0.3"
axum = "0.8.4"
num_cpus = "1.17.0"
tar = "0.4.44"
prometheus = { version = "0.14.0", features = ["push"] }
hyper = { version = "1.6.0", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
lazy_static = "1.5.0"
http-body-util = "0.1.3"

[patch.crates-io]

[profile.release]
overflow-checks = true

[profile.dev]
overflow-checks = true
opt-level = 3
debug = false

[profile.test]
opt-level = 3
debug = false
